version: '3.7'

networks:
  simple-network:
    driver: bridge

services:
  sharding_sample:
    image: sharding-sample:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=postgres;username=postgres;password=postgres"
    networks:
      - simple-network

  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks:
      - simple-network